/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mystart;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author The Prince
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Mname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Add = new javax.swing.JTextField();
        roomN = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkin = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        chkout = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Last Name : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 210, 75, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Middle Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 160, 85, 15);
        jPanel1.add(Phone);
        Phone.setBounds(430, 160, 170, 20);
        jPanel1.add(Mname);
        Mname.setBounds(150, 160, 170, 20);
        jPanel1.add(Lname);
        Lname.setBounds(150, 210, 170, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Phone : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 160, 60, 15);

        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(430, 110, 170, 20);

        roomN.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        roomN.setText("Room Number : ");
        jPanel1.add(roomN);
        roomN.setBounds(200, 50, 160, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Address : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 110, 61, 15);

        chkin.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        chkin.setText("Check In : ");
        jPanel1.add(chkin);
        chkin.setBounds(50, 10, 270, 19);
        jPanel1.add(Fname);
        Fname.setBounds(150, 110, 170, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("First Name : ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 110, 75, 15);

        chkout.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        chkout.setText("Check Out : ");
        jPanel1.add(chkout);
        chkout.setBounds(360, 10, 240, 19);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Back");
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 280, 80, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Bill");
        jButton2.setSelected(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 280, 80, 23);

        image.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mystart/hi_reception01_2_675x359_FitToBoxSmallDimension_Center.jpg"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(0, 0, 680, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        roomN.setText(roomN.getText()+"  "+help.roomNum.toString());
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        chkin.setText(chkin.getText()+"  "+s.format(help.din));
        chkout.setText(chkout.getText()+"  "+s.format(help.dout));     
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Rooms r = new Rooms();
        r.setVisible(true);
        help.setIcon(r);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(Fname.getText().equals("")||Mname.getText().equals("")||Lname.getText().equals("")||Add.getText().equals("")||Phone.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Fiil The Form","Error",JOptionPane.ERROR_MESSAGE);
        }
        
       else
        {
            //////////////// inserting Customer information
            PreparedStatement d;
            try {
                d = help.getConnected().prepareStatement("insert into customer (F_Name , M_Name , L_Name , Address , phone) values (?,?,?,?,?)");
                d.setString(1, Fname.getText());
                d.setString(2, Mname.getText());
                d.setString(3, Lname.getText());
                d.setString(4, Add.getText());
                d.setString(5, Phone.getText());
                d.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
            //////////////// take id and full name:
            PreparedStatement p,pp;
            try {
                p = help.getConnected().prepareStatement("select * from customer where phone=?");
                p.setString(1,Phone.getText());
                ResultSet rs=p.executeQuery();
                rs.next();
                help.Cust_ID=rs.getString(1);
                
                help.Cust_Name=Fname.getText()+" "+Mname.getText()+" "+Lname.getText();
                
                /////////////// update room state :
                pp = help.getConnected().prepareStatement("update rooms set State='Received' where Room_Number=?");
                String str=help.roomNum.toString();
                pp.setString(1,str);
                pp.executeUpdate();
                
            } catch (SQLException ex) {
                Logger.getLogger(Passward.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //////////////// open bill frame:
            this.dispose();
            Bill b = new Bill();
            b.setVisible(true);
            help.setIcon(b);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Mname;
    private javax.swing.JTextField Phone;
    private javax.swing.JLabel chkin;
    private javax.swing.JLabel chkout;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel roomN;
    // End of variables declaration//GEN-END:variables
}
