/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mystart;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author The Prince
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
        table.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        days = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        rooms = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        days1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Center");
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Back");
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 430, 80, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Booking");
        jButton2.setSelected(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(820, 430, 80, 23);
        jPanel1.add(checkin);
        checkin.setBounds(130, 30, 160, 20);
        jPanel1.add(checkout);
        checkout.setBounds(400, 30, 160, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Check Out :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 30, 80, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Check In :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 30, 70, 15);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Show Rooms");
        jButton3.setSelected(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(220, 430, 130, 23);

        days.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        days.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(days);
        days.setBounds(580, 30, 70, 20);

        table.setEnabled(false);

        rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setViewportView(rooms);

        jPanel1.add(table);
        table.setBounds(60, 70, 790, 330);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Show Bills");
        jButton4.setSelected(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(390, 430, 130, 23);

        days1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        days1.setForeground(new java.awt.Color(0, 0, 51));
        days1.setText("Single : 300 $   Double : 550 $");
        jPanel1.add(days1);
        days1.setBounds(650, 30, 200, 20);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("End Of Booking");
        jButton5.setSelected(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(560, 430, 130, 23);

        Image.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mystart/densa_main02_r.jpg"))); // NOI18N
        jPanel1.add(Image);
        Image.setBounds(0, 0, 910, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.dispose();
        firstfrm fr = new firstfrm();
        fr.setVisible(true);
        help.setIcon(fr);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(rooms.getSelectedRow()==-1)
            JOptionPane.showMessageDialog(null,"Please Select a Room ","Error",JOptionPane.ERROR_MESSAGE);
        else
        {
        Booking b = new Booking();
        this.dispose();
        b.setVisible(true);
        help.setIcon(b);
        int r=rooms.getSelectedRow();
        help.roomNum = rooms.getValueAt(r, 0);   
        help.din=checkin.getDate();
        help.dout=checkout.getDate();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(checkout.getDate()==null||checkin.getDate()==null)
        {
            JOptionPane.showMessageDialog(null," Please Choose Date First ","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            ///// Show Date :
            Date co = checkout.getDate();
            Date ci = checkin.getDate();
            SimpleDateFormat s = new SimpleDateFormat("dd");
            int in = Integer.parseInt(s.format(ci));
            int out = Integer.parseInt(s.format(co));
            help.days=out-in;
            days.setText(Integer.toString(out - in) + " days");
            table.setVisible(true);
            try {
                /////////////// Show Rooms :
                PreparedStatement d=help.getConnected().prepareStatement("select * from rooms where State = 'free' ");
                ResultSet r=d.executeQuery();
                DefaultTableModel dm=new DefaultTableModel();
                dm.addColumn("Room Number");
                dm.addColumn("Bed Type");
                dm.addColumn("Number Of Guests");
                dm.addColumn("Room State");
                while(r.next())
                {
                    String arr[]={r.getString(1) , r.getString(2) , r.getString(3) , r.getString(4)};
                    dm.addRow(arr);
                }
                rooms.setModel(dm);
            } catch (SQLException ex) {
                Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        table.setVisible(true);
            try {
                /////////////// Show Rooms :
                PreparedStatement d=help.getConnected().prepareStatement("select * from bill ");
                ResultSet r=d.executeQuery();
                DefaultTableModel dm=new DefaultTableModel();
                dm.addColumn("ID");
                dm.addColumn("Check_In");
                dm.addColumn("Check_Out");
                dm.addColumn("Rec_Id");
                dm.addColumn("Cust_Id");
                dm.addColumn("Cust_Name");
                dm.addColumn("Room_No");
                dm.addColumn("Total_Payment");
                while(r.next())
                {
                    String arr[]={r.getString(1) , r.getString(2) , r.getString(3) , r.getString(4),r.getString(5) , r.getString(6) , r.getString(7) , r.getString(8)};
                    dm.addRow(arr);
                }
                rooms.setModel(dm);
            } catch (SQLException ex) {
                Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        EndBook e = new EndBook();
        e.setDefaultCloseOperation(2);
        help.setIcon(e);
        e.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Image;
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JLabel days;
    private javax.swing.JLabel days1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable rooms;
    private javax.swing.JScrollPane table;
    // End of variables declaration//GEN-END:variables
}
